// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/boosted_trees/proto/quantiles.proto

#ifndef PROTOBUF_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto__INCLUDED
#define PROTOBUF_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace boosted_trees {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();
void protobuf_InitDefaults_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();
void protobuf_AssignDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();
void protobuf_ShutdownFile_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();

class QuantileConfig;
class QuantileEntry;
class QuantileStreamState;
class QuantileSummaryState;

// ===================================================================

class QuantileConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:boosted_trees.QuantileConfig) */ {
 public:
  QuantileConfig();
  virtual ~QuantileConfig();

  QuantileConfig(const QuantileConfig& from);

  inline QuantileConfig& operator=(const QuantileConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const QuantileConfig& default_instance();

  static const QuantileConfig* internal_default_instance();

  void UnsafeArenaSwap(QuantileConfig* other);
  void Swap(QuantileConfig* other);

  // implements Message ----------------------------------------------

  inline QuantileConfig* New() const { return New(NULL); }

  QuantileConfig* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QuantileConfig& from);
  void MergeFrom(const QuantileConfig& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(QuantileConfig* other);
  void UnsafeMergeFrom(const QuantileConfig& from);
  protected:
  explicit QuantileConfig(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double eps = 1;
  void clear_eps();
  static const int kEpsFieldNumber = 1;
  double eps() const;
  void set_eps(double value);

  // optional int64 num_quantiles = 2;
  void clear_num_quantiles();
  static const int kNumQuantilesFieldNumber = 2;
  ::google::protobuf::int64 num_quantiles() const;
  void set_num_quantiles(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:boosted_trees.QuantileConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double eps_;
  ::google::protobuf::int64 num_quantiles_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<QuantileConfig> QuantileConfig_default_instance_;

// -------------------------------------------------------------------

class QuantileEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:boosted_trees.QuantileEntry) */ {
 public:
  QuantileEntry();
  virtual ~QuantileEntry();

  QuantileEntry(const QuantileEntry& from);

  inline QuantileEntry& operator=(const QuantileEntry& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const QuantileEntry& default_instance();

  static const QuantileEntry* internal_default_instance();

  void UnsafeArenaSwap(QuantileEntry* other);
  void Swap(QuantileEntry* other);

  // implements Message ----------------------------------------------

  inline QuantileEntry* New() const { return New(NULL); }

  QuantileEntry* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QuantileEntry& from);
  void MergeFrom(const QuantileEntry& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(QuantileEntry* other);
  void UnsafeMergeFrom(const QuantileEntry& from);
  protected:
  explicit QuantileEntry(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  float value() const;
  void set_value(float value);

  // optional float weight = 2;
  void clear_weight();
  static const int kWeightFieldNumber = 2;
  float weight() const;
  void set_weight(float value);

  // optional float min_rank = 3;
  void clear_min_rank();
  static const int kMinRankFieldNumber = 3;
  float min_rank() const;
  void set_min_rank(float value);

  // optional float max_rank = 4;
  void clear_max_rank();
  static const int kMaxRankFieldNumber = 4;
  float max_rank() const;
  void set_max_rank(float value);

  // @@protoc_insertion_point(class_scope:boosted_trees.QuantileEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float value_;
  float weight_;
  float min_rank_;
  float max_rank_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<QuantileEntry> QuantileEntry_default_instance_;

// -------------------------------------------------------------------

class QuantileSummaryState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:boosted_trees.QuantileSummaryState) */ {
 public:
  QuantileSummaryState();
  virtual ~QuantileSummaryState();

  QuantileSummaryState(const QuantileSummaryState& from);

  inline QuantileSummaryState& operator=(const QuantileSummaryState& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const QuantileSummaryState& default_instance();

  static const QuantileSummaryState* internal_default_instance();

  void UnsafeArenaSwap(QuantileSummaryState* other);
  void Swap(QuantileSummaryState* other);

  // implements Message ----------------------------------------------

  inline QuantileSummaryState* New() const { return New(NULL); }

  QuantileSummaryState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QuantileSummaryState& from);
  void MergeFrom(const QuantileSummaryState& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(QuantileSummaryState* other);
  void UnsafeMergeFrom(const QuantileSummaryState& from);
  protected:
  explicit QuantileSummaryState(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .boosted_trees.QuantileEntry entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::boosted_trees::QuantileEntry& entries(int index) const;
  ::boosted_trees::QuantileEntry* mutable_entries(int index);
  ::boosted_trees::QuantileEntry* add_entries();
  ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileEntry >*
      mutable_entries();
  const ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileEntry >&
      entries() const;

  // @@protoc_insertion_point(class_scope:boosted_trees.QuantileSummaryState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileEntry > entries_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<QuantileSummaryState> QuantileSummaryState_default_instance_;

// -------------------------------------------------------------------

class QuantileStreamState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:boosted_trees.QuantileStreamState) */ {
 public:
  QuantileStreamState();
  virtual ~QuantileStreamState();

  QuantileStreamState(const QuantileStreamState& from);

  inline QuantileStreamState& operator=(const QuantileStreamState& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const QuantileStreamState& default_instance();

  static const QuantileStreamState* internal_default_instance();

  void UnsafeArenaSwap(QuantileStreamState* other);
  void Swap(QuantileStreamState* other);

  // implements Message ----------------------------------------------

  inline QuantileStreamState* New() const { return New(NULL); }

  QuantileStreamState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QuantileStreamState& from);
  void MergeFrom(const QuantileStreamState& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(QuantileStreamState* other);
  void UnsafeMergeFrom(const QuantileStreamState& from);
  protected:
  explicit QuantileStreamState(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .boosted_trees.QuantileSummaryState summaries = 1;
  int summaries_size() const;
  void clear_summaries();
  static const int kSummariesFieldNumber = 1;
  const ::boosted_trees::QuantileSummaryState& summaries(int index) const;
  ::boosted_trees::QuantileSummaryState* mutable_summaries(int index);
  ::boosted_trees::QuantileSummaryState* add_summaries();
  ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileSummaryState >*
      mutable_summaries();
  const ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileSummaryState >&
      summaries() const;

  // @@protoc_insertion_point(class_scope:boosted_trees.QuantileStreamState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileSummaryState > summaries_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<QuantileStreamState> QuantileStreamState_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// QuantileConfig

// optional double eps = 1;
inline void QuantileConfig::clear_eps() {
  eps_ = 0;
}
inline double QuantileConfig::eps() const {
  // @@protoc_insertion_point(field_get:boosted_trees.QuantileConfig.eps)
  return eps_;
}
inline void QuantileConfig::set_eps(double value) {
  
  eps_ = value;
  // @@protoc_insertion_point(field_set:boosted_trees.QuantileConfig.eps)
}

// optional int64 num_quantiles = 2;
inline void QuantileConfig::clear_num_quantiles() {
  num_quantiles_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 QuantileConfig::num_quantiles() const {
  // @@protoc_insertion_point(field_get:boosted_trees.QuantileConfig.num_quantiles)
  return num_quantiles_;
}
inline void QuantileConfig::set_num_quantiles(::google::protobuf::int64 value) {
  
  num_quantiles_ = value;
  // @@protoc_insertion_point(field_set:boosted_trees.QuantileConfig.num_quantiles)
}

inline const QuantileConfig* QuantileConfig::internal_default_instance() {
  return &QuantileConfig_default_instance_.get();
}
// -------------------------------------------------------------------

// QuantileEntry

// optional float value = 1;
inline void QuantileEntry::clear_value() {
  value_ = 0;
}
inline float QuantileEntry::value() const {
  // @@protoc_insertion_point(field_get:boosted_trees.QuantileEntry.value)
  return value_;
}
inline void QuantileEntry::set_value(float value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:boosted_trees.QuantileEntry.value)
}

// optional float weight = 2;
inline void QuantileEntry::clear_weight() {
  weight_ = 0;
}
inline float QuantileEntry::weight() const {
  // @@protoc_insertion_point(field_get:boosted_trees.QuantileEntry.weight)
  return weight_;
}
inline void QuantileEntry::set_weight(float value) {
  
  weight_ = value;
  // @@protoc_insertion_point(field_set:boosted_trees.QuantileEntry.weight)
}

// optional float min_rank = 3;
inline void QuantileEntry::clear_min_rank() {
  min_rank_ = 0;
}
inline float QuantileEntry::min_rank() const {
  // @@protoc_insertion_point(field_get:boosted_trees.QuantileEntry.min_rank)
  return min_rank_;
}
inline void QuantileEntry::set_min_rank(float value) {
  
  min_rank_ = value;
  // @@protoc_insertion_point(field_set:boosted_trees.QuantileEntry.min_rank)
}

// optional float max_rank = 4;
inline void QuantileEntry::clear_max_rank() {
  max_rank_ = 0;
}
inline float QuantileEntry::max_rank() const {
  // @@protoc_insertion_point(field_get:boosted_trees.QuantileEntry.max_rank)
  return max_rank_;
}
inline void QuantileEntry::set_max_rank(float value) {
  
  max_rank_ = value;
  // @@protoc_insertion_point(field_set:boosted_trees.QuantileEntry.max_rank)
}

inline const QuantileEntry* QuantileEntry::internal_default_instance() {
  return &QuantileEntry_default_instance_.get();
}
// -------------------------------------------------------------------

// QuantileSummaryState

// repeated .boosted_trees.QuantileEntry entries = 1;
inline int QuantileSummaryState::entries_size() const {
  return entries_.size();
}
inline void QuantileSummaryState::clear_entries() {
  entries_.Clear();
}
inline const ::boosted_trees::QuantileEntry& QuantileSummaryState::entries(int index) const {
  // @@protoc_insertion_point(field_get:boosted_trees.QuantileSummaryState.entries)
  return entries_.Get(index);
}
inline ::boosted_trees::QuantileEntry* QuantileSummaryState::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:boosted_trees.QuantileSummaryState.entries)
  return entries_.Mutable(index);
}
inline ::boosted_trees::QuantileEntry* QuantileSummaryState::add_entries() {
  // @@protoc_insertion_point(field_add:boosted_trees.QuantileSummaryState.entries)
  return entries_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileEntry >*
QuantileSummaryState::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:boosted_trees.QuantileSummaryState.entries)
  return &entries_;
}
inline const ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileEntry >&
QuantileSummaryState::entries() const {
  // @@protoc_insertion_point(field_list:boosted_trees.QuantileSummaryState.entries)
  return entries_;
}

inline const QuantileSummaryState* QuantileSummaryState::internal_default_instance() {
  return &QuantileSummaryState_default_instance_.get();
}
// -------------------------------------------------------------------

// QuantileStreamState

// repeated .boosted_trees.QuantileSummaryState summaries = 1;
inline int QuantileStreamState::summaries_size() const {
  return summaries_.size();
}
inline void QuantileStreamState::clear_summaries() {
  summaries_.Clear();
}
inline const ::boosted_trees::QuantileSummaryState& QuantileStreamState::summaries(int index) const {
  // @@protoc_insertion_point(field_get:boosted_trees.QuantileStreamState.summaries)
  return summaries_.Get(index);
}
inline ::boosted_trees::QuantileSummaryState* QuantileStreamState::mutable_summaries(int index) {
  // @@protoc_insertion_point(field_mutable:boosted_trees.QuantileStreamState.summaries)
  return summaries_.Mutable(index);
}
inline ::boosted_trees::QuantileSummaryState* QuantileStreamState::add_summaries() {
  // @@protoc_insertion_point(field_add:boosted_trees.QuantileStreamState.summaries)
  return summaries_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileSummaryState >*
QuantileStreamState::mutable_summaries() {
  // @@protoc_insertion_point(field_mutable_list:boosted_trees.QuantileStreamState.summaries)
  return &summaries_;
}
inline const ::google::protobuf::RepeatedPtrField< ::boosted_trees::QuantileSummaryState >&
QuantileStreamState::summaries() const {
  // @@protoc_insertion_point(field_list:boosted_trees.QuantileStreamState.summaries)
  return summaries_;
}

inline const QuantileStreamState* QuantileStreamState::internal_default_instance() {
  return &QuantileStreamState_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace boosted_trees

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fquantiles_2eproto__INCLUDED
