// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker_service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/core/protobuf/worker_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace grpc {

namespace {


}  // namespace


void protobuf_AssignDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
  protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tensorflow/core/protobuf/worker_service.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
}

void protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::tensorflow::protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_2eproto();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_once_);
void protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_once_,
                 &protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_impl);
}
void protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n-tensorflow/core/protobuf/worker_servic"
    "e.proto\022\017tensorflow.grpc\032%tensorflow/cor"
    "e/protobuf/worker.proto2\261\006\n\rWorkerServic"
    "e\022H\n\tGetStatus\022\034.tensorflow.GetStatusReq"
    "uest\032\035.tensorflow.GetStatusResponse\022f\n\023C"
    "reateWorkerSession\022&.tensorflow.CreateWo"
    "rkerSessionRequest\032\'.tensorflow.CreateWo"
    "rkerSessionResponse\022T\n\rRegisterGraph\022 .t"
    "ensorflow.RegisterGraphRequest\032!.tensorf"
    "low.RegisterGraphResponse\022Z\n\017DeregisterG"
    "raph\022\".tensorflow.DeregisterGraphRequest"
    "\032#.tensorflow.DeregisterGraphResponse\022E\n"
    "\010RunGraph\022\033.tensorflow.RunGraphRequest\032\034"
    ".tensorflow.RunGraphResponse\022Q\n\014CleanupG"
    "raph\022\037.tensorflow.CleanupGraphRequest\032 ."
    "tensorflow.CleanupGraphResponse\022K\n\nClean"
    "upAll\022\035.tensorflow.CleanupAllRequest\032\036.t"
    "ensorflow.CleanupAllResponse\022M\n\nRecvTens"
    "or\022\035.tensorflow.RecvTensorRequest\032\036.tens"
    "orflow.RecvTensorResponse\"\000\022B\n\007Logging\022\032"
    ".tensorflow.LoggingRequest\032\033.tensorflow."
    "LoggingResponse\022B\n\007Tracing\022\032.tensorflow."
    "TracingRequest\032\033.tensorflow.TracingRespo"
    "nseB3\n\032org.tensorflow.distruntimeB\023Worke"
    "rServiceProtosP\001b\006proto3", 984);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/protobuf/worker_service.proto", &protobuf_RegisterTypes);
  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_once_);
void protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_once_,
                 &protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto {
  StaticDescriptorInitializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
    protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto();
  }
} static_descriptor_initializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace grpc
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
